# Generated by Django 4.1.1 on 2022-09-21 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('business_type', models.CharField(max_length=100)),
                ('icon', models.ImageField(upload_to='listing/icon/')),
                ('image', models.ImageField(upload_to='listing/image/')),
                ('address', models.CharField(max_length=100)),
                ('status', models.BooleanField()),
                ('rating', models.CharField(max_length=100)),
                ('pricing', models.CharField(max_length=100)),
                ('web', models.URLField(max_length=250)),
                ('created', models.DateField(auto_now=True)),
            ],
        ),
    ]
